### ISSUE TITLE
Update PHP DI

### ISSUE THREAD

**Issue by benjaminknauer** [timtegeler/routerunner#11]
Update php-di to be supported in projects using newer versions of php-di itself.
http://php-di.org/doc/migration/6.0.html

**Comment by timtegeler** [comment]
Have a look at https://github.com/timtegeler/routerunner/commit/7ba7283dd6c761462688bef61bfea6e1a1006aa5

**Comment by timtegeler** [comment]
Done. Will be part of the next major release v5.
